# Generated by Django 4.2.7 on 2023-12-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('org', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
